### ISSUE TITLE
Code review by the team:- Night-Jars-89

### ISSUE THREAD

**Issue by jaspreet-singh-sahota** [jstloyal/Alien-Chaser#2]
Amazing job with the capstone project Tayo, here is my feedback:-

- I liked the theme of the project
- Game is really addictive
- Parallax background effect looks superb
- There are no issues in the functionality
- You should fix is the cutting image in the form section

Best of luck Tayo, hope you get mastery in all categories.
Best Regards, 
Jaspreet Singh

**Comment by jstloyal** [comment]
Thank you, Jaspreet for your observation and feedback.
